### ISSUE TITLE
Add tests to db->tree

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro3#1]
Cover the following cases:

For ALL of the below, test for already normalized database, and a database that is not normalized:

Each of these should appear at the root of a query (when possible), and nested in a query.

- [x] Properties (don't forget wildcards)
- [x] Joins (to one)
- [x] Joins (to many)
- [x] Unions (to one)
- [x] Unions (to many)
- [x] Getting a join as a prop (e.g. seeing an ident)
- [x] Recursion `...` (to-one, to-many, and circular)
- [x] Recursion `2` (to-one, to-many)
- [x] `denormalization-time` (make sure it appears in all of the above cases at each level where a component would consider that data `props`)

@wilkerlucio might already have some ideas/code for testing this kind of stuff.

**Comment by wilkerlucio** [comment]
Progress:

- [x] Properties (don't forget wildcards)
- [x] Joins (to one)
- [x] Joins (to many)
- [ ] Unions (to one)
- [ ] Unions (to many)
- [ ] Getting a join as a prop (e.g. seeing an ident)
- [ ] Recursion ... (to-one, to-many, and circular)
- [ ] Recursion 2 (to-one, to-many)
- [ ] denormalization-time (make sure it appears in all of the above cases at each level where a component would consider that data props)
