### ISSUE TITLE
Remote mutation sends blank returning query by default

### ISSUE THREAD

**Issue by wilkerlucio** [fulcrologic/fulcro3#30]
Since Fulcro 3, all remote mutations send to the server are going with a blank mutation join. In previous versions, it uses to send the mutation without any join.

For comparison, the following mutation:

```clojure
(fm/defmutation my-mutation [_]
  (remote [_] true))

; invoking

(fp/transact! this [`(my-mutation)])
```

Comparing network requests from the previous example:

```clojure
; Fulcro 2
[(my-mutation {})]

; Fulcro 3
[{(my-mutation {}) []}]
```

This prevents the user to read the real mutation response given the query makes the parser don't return anything.

**Comment by awkay** [comment]
I suspect this may be an EQL transformation bug in the EQL library.  I think children as a key may be there, but be empty, and EQL ast->query is then making it a mutation join.

**Comment by awkay** [comment]
Fixed on latest commit.  It was elide-ast-nodes, which is applied to queries and mutations now...and for mutations it was adding an empty children vector.  EQL could support this with a simple change as well.
