### ISSUE TITLE
Establishing an automated test pipeline for Fulcro3

### ISSUE THREAD

**Issue by abhi18av** [fulcrologic/fulcro3#32]
This is a proposal for establishing an automated test pipeline for `Fulcro3` so that it's easier to evaluate the PR's to the main repo. I propose that `CircleCI` is a good service to rely on for this testing pipeline. Please let me know your thoughts and accordingly, I'd initiate working in this direction.

**Comment by awkay** [comment]
Yes, of course this will be eventually done.  F2 has it, and we can copy the files over from there. If you're interested in getting it going I can see if I can make it so you can at least see the build output in CCI.

**Comment by awkay** [comment]
I copied in the F2 stuff and enabled it in CCI.  We'll see if it succeeds. If not, you can have a look at it.

**Comment by awkay** [comment]
https://circleci.com/gh/fulcrologic/fulcro3/1

**Comment by awkay** [comment]
Could you also copy the CCI badge code from f2 README.adoc into f3?  You'll have to update the CCI path.  There are two branch badges: one for master, and one for develop..just mimic the structure from f2.

**Comment by abhi18av** [comment]
The https://github.com/fulcrologic/fulcro3/pull/35 addresses the status badges :)

Let me explore the testing issue and get back to you.

**Comment by awkay** [comment]
Tests are passing...have been all day.

**Comment by abhi18av** [comment]
Then it's a time well spent - would have facilitate contribution a lot! Shall we close this issue then?

**Comment by awkay** [comment]
as far as contribution goes, running the tests locally should be what you're doing, and that is much much faster than waiting on CI.

make

will run tests (clj and cljs).
