### ISSUE TITLE
Make it possible to specify the path/name of defaults.edn

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro3#34]
The current server `load-config` function described http://book.fulcrologic.com/fulcro3/#_configuration_support_on_the_server_serverconfig and in ns com.fulcrologic.fulcro.server.config uses "config/defaults.edn" for defaults:

- Make it possible (optional) to override that name: `(load-config {:defaults "config/my-defaults.edn" :config-path "config/dev.edn"})`
- Run the tests and make sure none are broken (in config_spec)...You can run the tests in the IDE, or use `make dev` at CLI to have a watcher run them all.
- Add tests to verify that the override works.

Make sure you understand how it is supposed to work, so that the test verifies that the new default is used as the base of configuration, and that the overlay config (the :config-path option) will both see and be able to override values from the default.

**Comment by abhi18av** [comment]
So, I've studied the file and am working my way through the changes as it relates to the tests. For reference, here's the PR #41  that's the WIP for the intended changes.

**Comment by awkay** [comment]
Fixed.
